### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Angelk90** [blankg/rn-devmenu-ext#1]
@blankg : hi, I read your article, but I could not answer these two questions that came to me.
You could give me a hand.

1) I have a button in a view in the app, I have to make sure that when I do onpress on it is triggered the Reload event that is in the dev tools menu, what is in this image:
https://i.stack.imgur.com/qAIu3.jpg
Do you think it is possible?

2) It would be possible to make sure to remove the possibility of when the shake event movement is being debugged, do not start this menu: https://i.stack.imgur.com/qAIu3.jpg
But I want to do it in just one component, do you think it's possible?

**Comment by blankg** [comment]
@Angelk90 , you should be able to use the native module RCTDevSettings which has the reload method and setIsShakeToShowDevMenuEnabled method.

**Comment by Angelk90** [comment]
@blankg : 
For the reload method I found this: https://github.com/jhen0409/react-native-devsettings-android
But it does not support the method: setIsShakeToShowDevMenuEnabled
On the internet I can not find anything about: setIsShakeToShowDevMenuEnabled

How can I do some advice?

P.Š.
I'm on windows and the device is android.

**Comment by blankg** [comment]
@Angelk90 ,It seems that in Android react-native doesn't expose these methods to javascript (as they did in iOS) so this is why https://github.com/jhen0409/react-native-devsettings-android create a module to do that. You should contact jhen0409 and ask if he could also support setIsShakeToShowDevMenuEnabled.
